export const registerActions = {
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
};
export const loginActions = {
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
};
export const uploadAvatarActions = {
  UPLOAD_AVATAR_REQUEST: 'UPLOAD_AVATAR_REQUEST',
  UPLOAD_AVATAR_SUCCESS: 'UPLOAD_AVATAR_SUCCESS',
  UPLOAD_AVATAR_FAILURE: 'UPLOAD_AVATAR_FAILURE',
};
export const addBookActions = {
  ADD_BOOK_REQUEST: 'ADD_BOOK_REQUEST',
  ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
  ADD_BOOK_FAILURE: 'ADD_BOOK_FAILURE',
};
export const setBookRatingActions = {
  SET_BOOK_RATING_REQUEST: 'SET_BOOK_RATING_REQUEST',
  SET_BOOK_RATING_SUCCESS: 'SET_BOOK_RATING_SUCCESS',
  SET_BOOK_RATING_FAILURE: 'SET_BOOK_RATING_FAILURE',
};
export const setCommentActions = {
  SET_COMMENT_REQUEST: 'SET_COMMENT_REQUEST',
  SET_COMMENT_SUCCESS: 'SET_COMMENT_SUCCESS',
  SET_COMMENT_FAILURE: 'SET_COMMENT_FAILURE',
};
export const getBooksActions = {
  GET_BOOKS_REQUEST: 'GET_BOOKS_REQUEST',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE',
};
export const getFavoriteBooksActions = {
  GET_FAVORITE_BOOKS_REQUEST: 'GET_FAVORITE_BOOKS_REQUEST',
  GET_FAVORITE_BOOKS_SUCCESS: 'GET_FAVORITE_BOOKS_SUCCESS',
  GET_FAVORITE_BOOKS_FAILURE: 'GET_FAVORITE_BOOKS_FAILURE',
};
export const removeBookFromFavoriteActions = {
  REMOVE_BOOK_FROM_FAVORITE_REQUEST: 'REMOVE_BOOK_FROM_FAVORITE_REQUEST',
  REMOVE_BOOK_FROM_FAVORITE_SUCCESS: 'REMOVE_BOOK_FROM_FAVORITE_SUCCESS',
  REMOVE_BOOK_FROM_FAVORITE_FAILURE: 'REMOVE_BOOK_FROM_FAVORITE_FAILURE',
};
export const removeNotificationActions = {
  REMOVE_NOTIFICATION_REQUEST: 'REMOVE_NOTIFICATION_REQUEST',
  REMOVE_NOTIFICATION_SUCCESS: 'REMOVE_NOTIFICATION_SUCCESS',
  REMOVE_NOTIFICATION_FAILURE: 'REMOVE_NOTIFICATION_FAILURE',
};
export const getBookByIdActions = {
  GET_BOOK_BY_ID_REQUEST: 'GET_BOOK_BY_ID_REQUEST',
  GET_BOOK_BY_ID_SUCCESS: 'GET_BOOK_BY_ID_SUCCESS',
  GET_BOOK_BY_ID_FAILURE: 'GET_BOOK_BY_ID_FAILURE',
};
export const getNotificationsActions = {
  GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  GET_NOTIFICATIONS_FAILURE: 'GET_NOTIFICATIONS_FAILURE',
};
export const addCategoryActions = {
  ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
};
export const addBookToFavoriteActions = {
  ADD_BOOK_TO_FAVORITE_REQUEST: 'ADD_BOOK_TO_FAVORITE_REQUEST',
  ADD_BOOK_TO_FAVORITE_SUCCESS: 'ADD_BOOK_TO_FAVORITE_SUCCESS',
  ADD_BOOK_TO_FAVORITE_FAILURE: 'ADD_BOOK_TO_FAVORITE_FAILURE',
};
export const getCategoriesActions = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
};


export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
